### ISSUE TITLE
Event calendar

### ISSUE THREAD

**Issue by bitbeckers** [bitbeckers/daocember-dot-space#21]
Because F Google calendars and links all over the place

**Comment by peth-eth** [comment]
fr fr, DMd lux to see if he's down to do something like for metafest, gonna mock something up based on that

**Comment by peth-eth** [comment]
2 version: one based on the signup boxes design & one based on the ACTS - which do you like better?
![image](https://github.com/bitbeckers/daocember-dot-space/assets/55857222/3bf16178-5c63-4c2b-a545-935a06072489)
