### ISSUE TITLE
Banner & CTA on sharing

### ISSUE THREAD

**Issue by peth-eth** [bitbeckers/daocember-dot-space#38]
Right now, when sharing DAOcember's link it shows like this:
![image](https://github.com/bitbeckers/daocember-dot-space/assets/55857222/dec7bf69-689f-4174-9a2d-11fc6ba3cb28)

I propose we add this image:
https://substackcdn.com/image/fetch/w_1456,c_limit,f_webp,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-![image](media.s3.amazonaws.com%2Fpublic%2Fimages%2F51fd594d-0dd3-4636-97a2-86a268774768_1075x560.png)

And replace "A MetaFam event" with "A virtual gathering of DAOists boosting the new generation. Learn from the best & get your DAO growin'"

**Comment by aciid0** [comment]
Fixed with https://github.com/bitbeckers/daocember-dot-space/pull/42
