### ISSUE TITLE
the partner images

### ISSUE THREAD

**Issue by thebeyondr** [bitbeckers/daocember-dot-space#6]
seems that because these bad boys are from twitter Im getting what I think is a CORS error, causing them to not load. ffs. 

![image](https://github.com/bitbeckers/daocember-dot-space/assets/19380973/b4cac88c-d97f-4194-9e2d-08480cd2421b)

### Metafactory's honest reaction to that information: (he doesn't give a fuck, look at him)
![image](https://github.com/bitbeckers/daocember-dot-space/assets/19380973/065e005d-8755-4adf-b401-a2546b080ea6)

**Comment by peth-eth** [comment]
down to download & upload like MetaFactory, but seems fixed by now?

**Comment by aciid0** [comment]
Closing this. It was fixed in https://github.com/bitbeckers/daocember-dot-space/pull/27 

Firefox with strict privacy would block all the ones coming from Twitter
